name: railway_desktop_ui
description: "Railway.app Desktop"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0-219.0.dev

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  ################################
  app_runner: ^2.2.2
  device_preview: ^1.2.0 
  flutter_screenutil: ^5.9.0

  ##
  connectivity_plus: ^6.0.5
  dio: ^5.7.0

  ##
  equatable: ^2.0.5
  bloc: ^8.1.4
  hydrated_bloc: ^9.1.5
  bloc_concurrency: ^0.2.5
  flutter_bloc: ^8.1.6

  ##
  get_it: ^7.7.0

  ##
  flutter_secure_storage: ^9.2.2 
  path_provider: ^2.1.5
  path_provider_android: ^2.2.15
  path_provider_foundation: ^2.4.1
  shared_preferences: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  ##
  auto_route: ^9.2.0

  ##
  json_annotation: ^4.9.0 
  meta: ^1.12.0 
  intl: ^0.19.0
  basic_utils: ^5.7.0
  ##
  google_fonts: ^6.2.1 
  material_design_icons_flutter: ^7.0.7296 

  introduction_screen: ^3.1.14
  modal_bottom_sheet: ^3.0.0
  social_login_buttons: ^1.0.7
  flutter_svg: ^2.0.10+1
  diagram_editor: ^0.2.2
  
  faker: ^2.1.0
  flutter_exit_app: ^1.1.4

  ################################
dev_dependencies:
  flutter_test:
    sdk: flutter

  analyzer: ^6.8.0
  flutter_lints: ^4.0.0

# Automated Code generators
  auto_route_generator: ^9.0.0
  hive_generator: ^2.0.1

  json_serializable: ^6.8.0 
  #
  build_runner:
  build_web_compilers:
  test:

flutter:
  uses-material-design: true

  assets:
  ######
  - assets/fonts/
  ######
  - assets/launcher_icon/
  - assets/images/
  - assets/images/splash/
  - assets/images/intro/
  - assets/images/auth/
  - assets/images/onboarding/
  